apiVersion: v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
      http:
        paths:
          - path: /
            backend:
              service:
                name: app
                port:
                  number: 80
