apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    purpose: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
#        image: unoterr1/blog_pipe:latest
        imagePullPolicy: Always
#       image: localhost:5000/unoterr1/blog_pipe:latest
        image: 192.168.64.3:5000/unoterr1/blog_comp:$IMAGE
#        env:
#        - name: DATABASE_HOST
#          value: $HOST
#        - name: DATABASE_NAME
#          value: $NAME
#        - name: DATABASE_PASSWORD
#          value: $PASS
#        - name: DATABASE_USERNAME
#          value: $USER
        env:
        -  name: DATABASE_HOST
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_HOST
        -  name: DATABASE_NAME
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_NAME
        -  name: DATABASE_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_PASSWORD
        -  name: DATABASE_USERNAME
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_USERNAME                            
        ports:
          - containerPort: 3000