apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    purpose: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: unoterr1/blog_pipe:latest
#        imagePullPolicy: Never
        env:
        -  name: PGUSER
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: PGUSER
        -  name: PGPASSWORD
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: PGPASSWORD
        -  name: PGDATABASE
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: PGDATABASE
        -  name: PGHOST
           valueFrom:
            secretKeyRef:
              name: mysecret
              key: PGHOST
        ports:
          - containerPort: 3000
