apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    purpose: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
#        image: mparadowsky/blog:env2
        image: unoterr1/blog_pipe:latest
        env:
        - name: PGPASSWORD
          value: blog_backend
        - name: PGUSER
          value: blog_backend
        - name: PGDATABASE
          value: blog_backend
        - name: PGHOST
#          value: localhost
          value: postgresql-service:30003
        ports:
          - containerPort: 3000