version: '3'
services: 
  db:
    image: 'postgres:latest'
    restart: always
    env_file: 
      - .env
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}

  blog:
    build: 
      context: .
      dockerfile: Dockerfile
    # env_file: blog.env
    ports: 
      - '3000:3000'
    tty: true
    environment: 
      - PGHOST=${DATABASE_HOST}
      - PGUSER=${DATABASE_USERNAME}
      - PGDATABASE=${DATABASE_NAME}
      - PGPASSWORD=${DATABASE_PASSWORD}
    links:
      - redis
      - db
      # - traefik
    labels: 
      - traefik.enable=true
      - traefik.http.routers.blogdash.rule=Host("blog.lvh.me")
      - traefik.http.services.blog.loadbalancer.server.port=3000
      
  