apiVersion: v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: lubie.zycie
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
