apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
    PGPASSWORD: "blog_backend"
    PGUSER: "blog_backend"
    PGDATABASE: "blog_backend"
    PGHOST: "postgresql-service.default.svc.cluster.local"
