apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
    DATABASE_PASSWORD: "blog_backend"
    DATABASE_USERNAME: "blog_backend"
    DATABASE_NAME: "blog_backend"
    DATABASE_HOST: "postgresql-service.default.svc.cluster.local"
